version: "3"
services:
  redis:
    image: redis:alpine3.17
    container_name: bank-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.3
    container_name: bank-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - postgres
      - redis
    environment:
      GIN_MODE: release
      DATABASE_SOURCE: postgresql://root:postgres@postgres:5432/bank?sslmode=disable
      REDIS_ADDRESS: redis:6379
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]