apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap/aws-auth.yaml
  - deployment/redis-deployment.yaml
  - service/redis-service.yaml
  - deployment/deployment.yaml
  - service/service.yaml
#  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml                                 run only the first time that cluster is created
  - issuer.yaml
#  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.6.4/deploy/static/provider/aws/deploy.yaml      run only the first time that cluster is created
  - ingress/http-ingress.yaml
  - ingress/grpc-ingress.yaml